Repository HackYourFuture-CPH/fp-class22, pull requests merged in 2022-11, with the labels that each got.

#5 feature(Get productById endpoint)
  packages/server/api/controllers/products.controller.js
  packages/server/api/routes/index.js
  packages/server/api/routes/products.router.js
Labels: approved

#13 feature(ProductDescription Button)
  packages/client/src/components/ViewPageButton/ViewPageButton.component.js
  packages/client/src/components/ViewPageButton/ViewPageButton.stories.js
  packages/client/src/components/ViewPageButton/ViewPageButton.styles.css
Labels: approved, frontend

#12 feature(productdescription dropdown)
  packages/client/src/components/ViewDropDown/ViewDropdown.component.js
  packages/client/src/components/ViewDropDown/ViewDropdown.stories.js
  packages/client/src/components/ViewDropDown/ViewDropdown.styles.css
  packages/client/src/containers/DropdownGroup/DropdownGroup.Container.js
  packages/client/src/containers/DropdownGroup/DropdownGroup.Style.css
Labels: approved, frontend

#10 feature(product list component)
  packages/client/src/assets/images.png
  packages/client/src/components/ProductList/ProductList.component.css
  packages/client/src/components/ProductList/ProductList.component.js
  packages/client/src/components/ProductList/Products.js
  packages/client/src/containers/LandingPage/LandingPage.Container.js
Labels: frontend

#11 feature(Endpoint): get-all-products-endpoint
  packages/server/api/controllers/products.controller.js
  packages/server/api/routes/products.router.js
Labels: backend

#15 feature(product-image)
  packages/client/src/components/Button/ProductImage/ProductImage.js
  packages/client/src/components/Button/ProductImage/ProductImage.stories.js
  packages/client/src/components/Button/ProductImage/ProductImage.styles.css
  packages/client/src/components/Button/ProductImage/images/Picture1.png
  packages/client/src/components/Button/ProductImage/images/Picture2.png
  packages/client/src/components/Button/ProductImage/images/Picture3.png
  packages/client/src/components/Button/ProductImage/images/Picture4.png
  packages/client/src/index.css
Labels: frontend

#16 Class22-3-navigation-bar-component
  packages/client/src/components/Navigation/Navigation.component.js
  packages/client/src/components/Navigation/Navigation.stories.js
  packages/client/src/components/Navigation/Navigation.style.css
Labels: approved, frontend

#8 feature(footer)
  packages/client/public/assets/icons/Instagram.png
  packages/client/public/assets/icons/Twitter.png
  packages/client/public/assets/icons/Website.png
  packages/client/public/assets/icons/facebook.png
  packages/client/public/assets/icons/tiktok.png
  packages/client/src/components/Footer/Footer.jsx
  packages/client/src/components/Footer/FooterStyle.css
  packages/client/src/containers/LandingPage/LandingPage.Container.js
  packages/client/src/containers/LandingPage/LandingPage.Style.css
Labels: frontend

#20 CLASS22-5-product-view-page
  packages/client/src/assets/vectors/. gitkeep
  packages/client/src/assets/vectors/back-arrow.svg
  packages/client/src/assets/vectors/expand-arrow.svg
  packages/client/src/assets/vectors/sharp-star.svg
  packages/client/src/components/Product/ProductDescription/ProductDescription.component.js
  packages/client/src/components/Product/ProductView/ProductContainer/ProductContainer.component.js
  packages/client/src/components/Product/ProductView/ProductContainer/ProductContainer.styles.css
  packages/client/src/components/Product/ProductView/ProductViewDescription/ProductViewDescription.component.js
  packages/client/src/components/Product/ProductView/ProductViewDescription/ProductViewDescription.styles.css
  packages/client/src/components/Product/ProductView/ProductViewWrapper/ProductViewWrapper.component.js
  packages/client/src/components/Product/ProductView/ProductViewWrapper/ProductViewWrapper.styles.css
  packages/client/src/components/ProductImage/ProductImage.component.js
  packages/client/src/components/ProductImage/ProductImage.stories.js
  packages/client/src/components/shared/GoBackButton/GoBackButton.component.js
  packages/client/src/components/shared/GoBackButton/GoBackButton.stories.js
  packages/client/src/components/shared/GoBackButton/GoBackButton.styles.css
  packages/client/src/components/shared/ReadMoreButton/ReadMoreButton.component.js
  packages/client/src/containers/ProductView/ProductView.container.js
  packages/client/src/containers/ProductView/ProductView.styles.css
  packages/client/src/containers/ProductView/index.js
Labels: frontend

#6 feature(Page Layout): creating page layout for Homepage
  .gitignore
  packages/client/src/App.js
  packages/client/src/components/Body/Body.component.js
  packages/client/src/components/Footer/Footer.component.js
  packages/client/src/components/Header/Header.component.js
  packages/client/src/components/Newsletter/Newsletter.component.js
  packages/client/src/containers/HomePage/HomePage.Container.js
  packages/client/src/containers/HomePage/HomePage.Style.css
Labels: approved, frontend

#9 CLASS22-18-product-card-component
  packages/client/src/assets/cart-icon.svg
  packages/client/src/assets/favorite-icon.svg
  packages/client/src/assets/jeans&shoes.jpg
  packages/client/src/assets/star-rate-icon.svg
  packages/client/src/components/ProductCard/ProductCard.component.js
  packages/client/src/components/ProductCard/ProductCard.styles.css
  packages/client/src/index.css
Labels: frontend

#21 Class22 20 header component
  .gitignore
  packages/client/public/index.html
  packages/client/src/assets/image-header.png
  packages/client/src/components/Header/Header.component.js
  packages/client/src/components/Header/Header.styles.css
  packages/client/src/containers/LandingPage/LandingPage.Container.js
Labels: frontend

#23 Class22-33-product-view-page-styling-without-responsiveness
  packages/client/src/App.js
  packages/client/src/components/Product/ProductDescription/ProductDescription.styles.css
  packages/client/src/components/Product/ProductView/ProductContainer/ProductContainer.component.js
  packages/client/src/components/Product/ProductView/ProductContainer/ProductContainer.styles.css
  packages/client/src/components/Product/ProductView/ProductViewDescription/ProductViewDescription.component.js
  packages/client/src/components/Product/ProductView/ProductViewDescription/ProductViewDescription.styles.css
  packages/client/src/components/Product/ProductView/ProductViewWrapper/ProductViewWrapper.component.js
  packages/client/src/components/Product/ProductView/ProductViewWrapper/ProductViewWrapper.styles.css
  packages/client/src/components/ProductImage/ProductImage.component.js
  packages/client/src/components/ProductImage/ProductImage.styles.css
  packages/client/src/components/ViewDropDown/ViewDropdown.component.js
  packages/client/src/components/ViewDropDown/ViewDropdown.styles.css
  packages/client/src/components/ViewPageButton/ViewPageButton.component.js
  packages/client/src/components/ViewPageButton/ViewPageButton.styles.css
  packages/client/src/components/shared/GoBackButton/GoBackButton.styles.css
  packages/client/src/containers/DropdownGroup/DropdownGroup.Container.js
  packages/client/src/containers/DropdownGroup/DropdownGroup.Style.css
  packages/client/src/containers/ProductView/ProductView.container.js
  packages/client/src/containers/ProductView/ProductView.styles.css
  packages/client/src/containers/ProductView/ProductViewButtons/ProductViewButtons.container.js
  packages/client/src/containers/ProductView/ProductViewButtons/ProductViewButtons.styles.css
  packages/client/src/containers/ProductView/index.js
Labels: approved, frontend

#18 Class22-24-body-component
  packages/client/public/assets/images/body-images/closet.png
  packages/client/public/assets/images/body-images/earring.png
  packages/client/public/assets/images/body-images/glass.png
  packages/client/public/assets/images/body-images/handbag.png
  packages/client/public/assets/images/body-images/men-accessories.png
  packages/client/public/assets/images/body-images/women-accessories.png
  packages/client/src/components/body/body.component.js
  packages/client/src/components/body/body.style.css
Labels: frontend

#31 feature(ProductList layout responsveness)
  packages/client/src/components/ProductList/ProductList.component.css
  packages/client/src/components/ProductList/ProductList.component.js
  packages/client/src/components/ProductList/Products.js
Labels: frontend, styling

#33 feature(Get products By category endpoint)
  packages/server/api/controllers/products.controller.js
  packages/server/api/routes/products.router.js
Labels: approved, backend

#32 fix (Add all components): adding components on homepage
  .prettierignore
  packages/client/.eslintignore
  packages/client/.gitignore
  packages/client/src/App.js
  packages/client/src/assets/icons/Instagram.png
  packages/client/src/assets/icons/Twitter.png
  packages/client/src/assets/icons/Website.png
  packages/client/src/assets/icons/facebook.png
  packages/client/src/assets/icons/tiktok.png
  packages/client/src/assets/images/body-images/closet.png
  packages/client/src/assets/images/body-images/earring.png
  packages/client/src/assets/images/body-images/glass.png
  packages/client/src/assets/images/body-images/handbag.png
  packages/client/src/assets/images/body-images/men-accessories.png
  packages/client/src/assets/images/body-images/women-accessories.png
  packages/client/src/components/Body/Body.component.js
  packages/client/src/components/Body/Body.styles.css
  packages/client/src/components/Footer/Footer.component.js
  packages/client/src/components/Footer/Footer.jsx
  packages/client/src/components/Footer/Footer.styles.css
  packages/client/src/components/Footer/FooterStyle.css
  packages/client/src/components/Header/Header.component.js
  packages/client/src/components/Header/Header.styles.css
  packages/client/src/components/Navigation/Navigation.component.js
  packages/client/src/components/Navigation/Navigation.style.css
  packages/client/src/components/Navigation/Navigation.styles.css
  packages/client/src/components/Newsletter/Newsletter.component.js
  packages/client/src/components/Newsletter/Newsletter.styles.css
  packages/client/src/components/ProductList/ProductList.component.js
  packages/client/src/components/shared/Layout/Layout.component.js
  packages/client/src/containers/HomePage/HomePage.Container.js
  packages/client/src/containers/HomePage/HomePage.styles.css
  packages/client/src/containers/LandingPage/LandingPage.Container.js
  packages/client/src/index.css
Labels: invalid, frontend

#36 fix(ProductList): remove misplaced components
  packages/client/src/components/ProductList/ProductList.component.js
Labels: bug, frontend

#37 feature(ProductView) with responsiveness
  packages/client/src/components/Product/ProductView/ProductContainer/ProductContainer.styles.css
  packages/client/src/components/Product/ProductView/ProductViewDescription/ProductViewDescription.styles.css
  packages/client/src/components/Product/ProductView/ProductViewWrapper/ProductViewWrapper.styles.css
  packages/client/src/components/ProductImage/ProductImage.component.js
  packages/client/src/components/ProductImage/ProductImage.styles.css
  packages/client/src/components/ViewDropDown/ViewDropdown.styles.css
  packages/client/src/components/ViewPageButton/ViewPageButton.styles.css
  packages/client/src/components/shared/GoBackButton/GoBackButton.styles.css
  packages/client/src/containers/ProductView/ProductView.container.js
Labels: approved, frontend, styling
