Repository HackYourFuture-CPH/fp-class22, pull requests merged in 2022-12, with the labels that each got.

#38 feature(carousel)components
  packages/client/src/components/ViewCarousel/ViewBackCarousel/ViewBackCarousel.js
  packages/client/src/components/ViewCarousel/ViewBackCarousel/ViewBackCarousel.stories.js
  packages/client/src/components/ViewCarousel/ViewBackCarousel/ViewBackCarousel.style.css
  packages/client/src/components/ViewCarousel/ViewForwadCarousel/ViewAfterCarousel.js
  packages/client/src/components/ViewCarousel/ViewForwadCarousel/ViewAfterCarousel.stories.js
  packages/client/src/components/ViewCarousel/ViewForwadCarousel/ViewAfterCarousel.styles.css
  packages/client/src/containers/ProductView/ProductViewCarousel/ProductViewCarousel.container.js
Labels: frontend

#45 feature(product list component): Fetched Products from the database
  packages/client/src/components/ProductCard/ProductCard.component.js
  packages/client/src/components/ProductList/ProductList.component.css
  packages/client/src/components/ProductList/ProductList.component.js
  packages/client/src/components/ProductList/Products.js
Labels: frontend, backend

#39 Class22 45 product view page related items layout
  packages/client/src/containers/ProductView/ProductView.container.js
  packages/client/src/containers/ProductView/index.js
  packages/client/src/containers/RelatedItems/RelatedItems.Container.js
  packages/client/src/containers/RelatedItems/RelatedItems.styles.css
Labels: frontend, styling

#43 feature(categories endpoint):created get categories endpoint
  packages/server/api/controllers/categories.controller.js
  packages/server/api/routes/categories.router.js
  packages/server/api/routes/index.js
Labels: backend

#42 feature(Products Search Endpoint): Create product search by name endp…
  packages/server/api/controllers/products.controller.js
  packages/server/api/routes/products.router.js
Labels: backend

#46 refactor(App): centralise Navigation and Footer
  packages/client/src/App.js
  packages/client/src/components/Footer/Footer.component.js
  packages/client/src/components/Footer/Footer.styles.css
  packages/client/src/components/Navigation/Navigation.component.js
  packages/client/src/containers/HomePage/HomePage.Container.js
  packages/client/src/containers/HomePage/HomePage.styles.css
  packages/client/src/containers/LandingPage/LandingPage.Container.js
Labels: frontend

#51 feature(dropdown-responsive-and-update-storybook): Upadate ProductLis…
  packages/client/src/components/ProductListDropDown/DropDownView/DropDownView.component.js
  packages/client/src/components/ProductListDropDown/DropDownView/DropDownView.stories.js
  packages/client/src/components/ProductListDropDown/DropDownView/DropDownView.style.css
  packages/client/src/components/ProductListDropDown/DropDownViewList/DropDownViewList.component.js
  packages/client/src/components/ProductListDropDown/DropDownViewList/DropDownViewList.style.css
  packages/client/src/components/ProductListDropDown/ProductListDropDown.component.js
  packages/client/src/components/ProductListDropDown/ProductListDropDown.style.css
  packages/client/src/containers/CollectionsPage/CollectionsPage.Container.js
  packages/client/src/containers/ProductListDropDown/ProductListDropDown.container.js
  packages/client/src/containers/ProductListDropDown/ProductListDropDown.style.css
Labels: approved, frontend, styling

#41 feat(contactUs)
  packages/client/public/assets/icons/email.png
  packages/client/public/assets/images/contactUs.png
  packages/client/src/App.js
  packages/client/src/components/PlaceholderPages/ContactUs.component.js
  packages/client/src/containers/AboutUs.container.js
  packages/client/src/containers/AboutUs.styles.css
  packages/client/src/containers/ContactUs.container.js
  packages/client/src/containers/ContactUs.styles.css
  packages/client/src/containers/Login.container.js
  packages/client/src/containers/Login.styles.css
Labels: approved, frontend, Landing_team

#54 CLASS22-58-cart-page-structure
  packages/client/src/components/Cart/CartButtons/CartButtons.component.js
  packages/client/src/components/Cart/CartButtons/CartButtons.styles.css
  packages/client/src/components/Cart/CartContainer/CartContainer.component.js
  packages/client/src/components/Cart/CartContainer/CartContainer.stories.js
  packages/client/src/components/Cart/CartContainer/CartContainer.styles.css
  packages/client/src/components/Cart/CartCount/CartCount.component.js
  packages/client/src/components/Cart/CartCount/CartCount.stories.js
  packages/client/src/components/Cart/CartCount/CartCount.styles.css
  packages/client/src/components/Cart/CartSelectedProduct/CartSelectedProduct.component.js
  packages/client/src/components/Cart/CartSelectedProduct/CartSelectedProduct.stories.js
  packages/client/src/components/Cart/CartSelectedProduct/CartSelectedProduct.styles.css
  packages/client/src/components/Cart/CartTable/CartTable.component.js
  packages/client/src/components/Cart/CartTable/CartTable.stories.js
  packages/client/src/components/Cart/CartTable/CartTable.styles.css
  packages/client/src/components/Cart/CartTotal/CartTotal.component.js
  packages/client/src/components/Cart/CartTotal/CartTotal.stories.js
  packages/client/src/components/Cart/CartTotal/CartTotal.styles.css
  packages/client/src/containers/ShoppingCartPage/ShoppingCartPage.container.js
  packages/client/src/containers/ShoppingCartPage/ShoppingCartPage.styles.css
Labels: frontend, View_team

#52 Class22 51 product reviews for product view page
  packages/client/src/assets/Reviewer.png
  packages/client/src/components/ProductReviews/DisplayReviews/DisplayReviews.component.js
  packages/client/src/components/ProductReviews/DisplayReviews/DisplayReviews.styles.css
  packages/client/src/components/ProductReviews/ProductReviews.component.js
  packages/client/src/components/ProductReviews/ProductReviews.stories.js
  packages/client/src/components/ProductReviews/ProductReviews.styles.css
Labels: frontend, styling, View_team

#53 Class22 61 related item responsiveness
  packages/client/src/components/Product/ProductDescription/ProductDescription.styles.css
  packages/client/src/components/Product/ProductView/ProductContainer/ProductContainer.styles.css
  packages/client/src/components/Product/ProductView/ProductViewDescription/ProductViewDescription.styles.css
  packages/client/src/components/Product/ProductView/ProductViewWrapper/ProductViewWrapper.styles.css
  packages/client/src/components/ProductImage/ProductImage.styles.css
  packages/client/src/components/ProductListDropDown/ProductListDropDown.style.css
  packages/client/src/components/ViewPageButton/ViewPageButton.styles.css
  packages/client/src/components/shared/GoBackButton/GoBackButton.styles.css
  packages/client/src/containers/HomePage/HomePage.styles.css
  packages/client/src/containers/ProductView/ProductView.container.js
  packages/client/src/containers/RelatedItems/RelatedItems.styles.css
  packages/client/src/index.css
Labels: frontend, styling, View_team

#57 Responsiveness of product card components
  packages/client/src/components/ProductCard/ProductCard.styles.css
  packages/client/src/components/ProductList/ProductList.component.css
  packages/client/src/components/ProductListDropDown/DropDownView/DropDownView.style.css
  packages/client/src/components/ProductListDropDown/DropDownViewList/DropDownViewList.style.css
Labels: frontend, Search_team

#55 feature (Firebase): firebase setup
  packages/client/package.json
  packages/client/src/App.js
  packages/client/src/components/Navigation/Navigation.component.js
  packages/client/src/components/Navigation/Navigation.styles.css
  packages/client/src/containers/Login.container.js
  packages/client/src/containers/Login/Login.container.js
  packages/client/src/containers/Login/Login.styles.css
  packages/client/src/containers/Reset/Reset.container.js
  packages/client/src/containers/Reset/Reset.styles.css
  packages/client/src/containers/Signup/Signup.container.js
  packages/client/src/containers/Signup/Signup.styles.css
  packages/client/src/firebase.js
Labels: frontend

#50 Class22 50-login-page-layout
  packages/client/public/assets/icons/Google.png
  packages/client/public/assets/images/signup-body-img.png
  packages/client/src/App.js
  packages/client/src/containers/Login.container/FormValidation.js
  packages/client/src/containers/Login.container/Login.css
  packages/client/src/containers/Login.container/Login.js
  packages/client/src/containers/Login.container/SignupForm.js
Labels: Landing_team

#59 feat(users): add migrations and seeds
  packages/server/migrations/20221204144142_add_user_table.js
  packages/server/seeds/development/users.js
Labels: database

#66 fix(Body): fix typo in the Button label
  packages/client/src/components/Body/Body.component.js
Labels: frontend, styling

#65 featuer(Fix Typo Error):Fix Typo error in HttpError
  packages/server/api/controllers/exampleResources.controller.js
  packages/server/api/controllers/products.controller.js
Labels: bug, backend

#67 feature(Remove Extra CSS file and Remove Media-queries)
  packages/client/src/components/ProductListDropDown/DropDownView/DropDownView.style.css
  packages/client/src/components/ProductListDropDown/ProductListDropDown.style.css
Labels: frontend, styling, Search_team

#69 CLASS22-76-update-product-card-background-styling
  packages/client/src/components/ProductCard/ProductCard.styles.css
  packages/client/src/containers/ContactUs.styles.css
Labels: frontend, styling, Search_team

#71 feature(migration): added migration of orders and order_items table
  packages/server/migrations/20221205212026_add_orders_table.js
  packages/server/migrations/20221205220007_add_order_items_table.js
  packages/server/seeds/development/v_orders.js
  packages/server/seeds/development/w_orders_items.js
Labels: backend, database

#76 feature(FavoritesPage): create favorites page
  packages/client/src/App.js
  packages/client/src/containers/FavoritesPage/FavoritesPage.container.js
Labels: frontend, Search_team

#74 home-page-body-shop-now-button-typo-fix
  packages/client/src/components/Body/Body.component.js
Labels: frontend, Landing_team

#75 feature(variants) add-migrations-and-seeds
  packages/client/src/components/ViewCarousel/ViewBackCarousel/ViewBackCarousel.js
  packages/server/migrations/20221206115201_add_variants_table.js
  packages/server/seeds/development/variants.js
Labels: database

#81 fix(product-list-styling): adjusted product-list-styling
  packages/client/src/components/ProductList/ProductList.component.css
  packages/client/src/components/SearchInput/SearchInput.style.css
Labels: frontend, styling, Search_team

#62 Class22 83-confirmation-message-for-valid-sign-up-form
  packages/client/src/containers/Login.container/Login.css
  packages/client/src/containers/Login.container/Login.js
  packages/client/src/containers/Login.container/SignupForm.js
Labels: frontend, Landing_team

#77 Class22 90 favorites migration and seeds
  packages/server/migrations/20221206130228_favorites_table.js
  packages/server/seeds/development/v-favorites.js
Labels: database, Landing_team

#85 fix(SearchInput): add 'nothing found' massage
  packages/client/src/components/ProductList/ProductList.component.js
Labels: frontend, Search_team

#72 style(DropDownView): add svg icon to the select
  packages/client/src/assets/all-filter-icon.svg
  packages/client/src/assets/filterIcon.png
  packages/client/src/components/ProductListDropDown/DropDownView/DropDownView.component.js
  packages/client/src/components/ProductListDropDown/DropDownView/DropDownView.style.css
  packages/client/src/components/ProductListDropDown/DropDownViewList/DropDownViewList.component.js
  packages/client/src/containers/CollectionsPage/CollectionsPage.Container.js
Labels: styling, Search_team

#88 feat(single form validation function) for login/contact us page
  packages/client/src/containers/ContactUs.container.js
  packages/client/src/containers/Login.container/SignupForm.js
  packages/client/src/utils/validateForm.js
Labels: approved, frontend, Landing_team

#63 feature(Functional Categories Dropdown)
  packages/client/src/components/CategoriesListDropDown/CategoriesListDropDown.component.js
  packages/client/src/components/CategoriesListDropDown/CategoriesListDropDown.stories.js
  packages/client/src/components/CategoriesListDropDown/CategoriesListDropDown.style.css
  packages/client/src/components/ProductList/ProductList.component.js
  packages/client/src/components/ProductListDropDown/DropDownViewList/DropDownViewList.component.js
  packages/client/src/containers/CollectionsPage/CollectionsPage.Container.js
  packages/client/src/containers/CollectionsPage/CollectionsPage.style.css
  packages/client/src/containers/FavoritesPage/FavoritesPage.container.js
  packages/server/api/routes/products.router.js
Labels: frontend, Search_team

#83 feat(Contact): Block submission of invalid form
  packages/client/src/containers/ContactUs.container.js
  packages/client/src/containers/ContactUs.styles.css
Labels: frontend, Landing_team

#93 feature(adjust-collections-categories-filter): fix dropdown title
  packages/client/src/components/CategoriesListDropDown/CategoriesListDropDown.component.js
  packages/client/src/containers/CollectionsPage/CollectionsPage.Container.js
Labels: frontend, Search_team

#70 CLASS22-84-restyling-product-view-page-with-adding-reviews
  packages/client/src/components/Product/ProductDescription/ProductDescription.styles.css
  packages/client/src/components/Product/ProductView/ProductViewDescription/ProductViewDescription.styles.css
  packages/client/src/components/Product/ProductView/ProductViewWrapper/ProductViewWrapper.styles.css
  packages/client/src/components/Product/ProductView/ProductViewWrappers/ProductViewDescription/ProductViewDescription.component.js
  packages/client/src/components/Product/ProductView/ProductViewWrappers/ProductViewDescription/ProductViewDescription.styles.css
  packages/client/src/components/Product/ProductView/ProductViewWrappers/ProductViewImageWrapper/ProductViewImageWrapper.component.js
  packages/client/src/components/Product/ProductView/ProductViewWrappers/ProductViewImageWrapper/ProductViewImageWrapper.styles.css
  packages/client/src/components/Product/ProductView/ProductViewWrappers/ProductViewReviewsWrapper/ProductViewReviewsWrapper.component.js
  packages/client/src/components/Product/ProductView/ProductViewWrappers/ProductViewReviewsWrapper/ProductViewReviewsWrapper.styles.css
  packages/client/src/components/Product/ProductView/ProductViewWrappers/ProductViewWrapper/ProductViewWrapper.component.js
  packages/client/src/components/Product/ProductView/ProductViewWrappers/ProductViewWrapper/ProductViewWrapper.styles.css
  packages/client/src/components/ProductImage/ProductImage.component.js
  packages/client/src/components/ProductImage/ProductImage.styles.css
  packages/client/src/components/ProductReviews/DisplayReviews/DisplayReviews.component.js
  packages/client/src/components/ProductReviews/DisplayReviews/DisplayReviews.styles.css
  packages/client/src/components/ProductReviews/ProductReviews.styles.css
  packages/client/src/components/ViewCarousel/ViewBackCarousel/ViewBackCarousel.component.js
  packages/client/src/components/ViewCarousel/ViewBackCarousel/ViewBackCarousel.stories.js
  packages/client/src/components/ViewCarousel/ViewBackCarousel/ViewBackCarousel.style.css
  packages/client/src/components/ViewCarousel/ViewBackCarousel/ViewBackCarousel.styles.css
  packages/client/src/components/ViewCarousel/ViewForwadCarousel/ViewAfterCarousel.js
  packages/client/src/components/ViewCarousel/ViewForwadCarousel/ViewAfterCarousel.stories.js
  packages/client/src/components/ViewCarousel/ViewForwadCarousel/ViewAfterCarousel.styles.css
  packages/client/src/components/ViewCarousel/ViewForwardCarousel/ViewForwardCarousel.component.js
  packages/client/src/components/ViewCarousel/ViewForwardCarousel/ViewForwardCarousel.stories.js
  packages/client/src/components/ViewCarousel/ViewForwardCarousel/ViewForwardCarousel.styles.css
  packages/client/src/components/ViewDropDown/ViewDropdown.component.js
  packages/client/src/components/ViewDropDown/ViewDropdown.styles.css
  packages/client/src/components/shared/ReadMoreButton/ReadMoreButton.styles.css
  packages/client/src/containers/DropdownGroup/DropdownGroup.Style.css
  packages/client/src/containers/HomePage/HomePage.styles.css
  packages/client/src/containers/ProductView/ProductView.container.js
  packages/client/src/containers/ProductView/ProductView.styles.css
  packages/client/src/containers/ProductView/ProductViewButtons/ProductViewButtons.styles.css
  packages/client/src/containers/ProductView/index.js
  packages/client/src/containers/RelatedItems/RelatedItems.Container.js
  packages/client/src/containers/RelatedItems/RelatedItems.styles.css
Labels: frontend, View_team

#91 feature(Modal): new generic component
  packages/client/src/components/Modal/Modal.component.js
  packages/client/src/components/Modal/modal.styles.css
  packages/client/src/components/Product/ProductView/ProductViewReviewsWrapper/ProductViewReviewsWrapper.component.js
  packages/client/src/components/Product/ProductView/ProductViewReviewsWrapper/ProductViewReviewsWrapper.styles.css
  packages/client/src/components/Product/ProductView/ProductViewWrappers/ProductViewWrapper/ProductViewWrapper.styles.css
  packages/client/src/components/ProductCard/ProductCard.styles.css
  packages/client/src/components/ProductReviews/DisplayReviews/DisplayReviews.component.js
  packages/client/src/components/ProductReviews/DisplayReviews/DisplayReviews.styles.css
  packages/client/src/components/ProductReviews/ProductReviews.component.js
  packages/client/src/containers/ProductReviewContainer/ProductReviewsContainer.js
  packages/client/src/containers/ProductView/ProductView.container.js
  packages/client/src/containers/ProductView/index.js
Labels: frontend, View_team

#86 feature(variants-endpoint)Get all variants by productId
  packages/server/api/controllers/variants.controller.js
  packages/server/api/routes/index.js
  packages/server/api/routes/variants.router.js
  packages/server/migrations/20221206115201_add_variants_table.js
  packages/server/seeds/development/variants.js
Labels: backend, View_team

#87 feature (userContext): with firebase
  packages/client/src/App.js
  packages/client/src/components/Navigation/Navigation.component.js
  packages/client/src/containers/Login/Login.container.js
  packages/client/src/containers/Signup/Signup.container.js
  packages/client/src/userContext.js
Labels: frontend, Landing_team

#89 feat(GET/POST/DELETE favorites): created get/post/delete end point of…
  packages/server/api/controllers/favorites.controller.js
  packages/server/api/routes/favorites.router.js
  packages/server/api/routes/index.js
Labels: approved, database, Search_team

#90 Class22 105 get all reviews and get reviews by product id endpoint
  packages/server/api/controllers/reviews.controller.js
  packages/server/api/routes/index.js
  packages/server/api/routes/reviews.router.js
Labels: approved, backend, View_team

#82 feature(Realted Items): made changes to handle the number of items in…
  packages/client/src/containers/RelatedItems/RelatedItems.Container.js
  packages/client/src/containers/RelatedItems/RelatedItems.styles.css
  packages/server/api/controllers/products.controller.js
  packages/server/api/routes/products.router.js
Labels: frontend, backend, styling, View_team

#96 feature(fetching data from variants endpoint)
  packages/client/src/components/ViewDropDown/ViewDropdown.component.js
  packages/client/src/containers/DropdownGroup/DropdownGroup.Container.js
  packages/client/src/containers/ProductView/ProductView.container.js
Labels: backend, View_team

#98 feature(Sorting filter Bug and logic): Fix sorting function bug remov…
  packages/client/src/containers/CollectionsPage/CollectionsPage.Container.js
Labels: bug, frontend, Search_team

#103 feature(ProductReviews): fetching reviews from DB
  packages/client/src/components/Product/ProductView/ProductViewReviewsWrapper/ProductViewReviewsWrapper.component.js
  packages/client/src/components/Product/ProductView/ProductViewReviewsWrapper/ProductViewReviewsWrapper.styles.css
  packages/client/src/components/ProductReviews/DisplayReviews/DisplayReviews.component.js
  packages/client/src/components/ProductReviews/ProductReviews.component.js
  packages/client/src/containers/ProductReviewContainer/ProductReviewsContainer.js
  packages/client/src/containers/ProductView/ProductView.container.js
  packages/server/api/controllers/reviews.controller.js
Labels: frontend, View_team

#104 feature(Fix Collection Page):Fix Dropdowns Background Color
  packages/client/src/components/CategoriesListDropDown/CategoriesListDropDown.style.css
Labels: bug, frontend

#108 fix(Bug): fixed the viewpage productId undefined
  packages/client/src/containers/ProductView/ProductView.container.js
Labels: bug, frontend, View_team

#114 Added 404 image and modified PageNotFoundContainer
  packages/client/src/assets/404.jpeg
  packages/client/src/containers/PageNotFound/PageNotFound.Container.js
Labels: frontend, View_team

#110 feat(users): add uid column
  packages/server/migrations/20221218144029_add_uid_to_users.js
Labels: database

#113 fix(order_items): drop product_id and add variant_id
  packages/server/migrations/20221218234203_alter_oder_items_table.js
  packages/server/seeds/development/w_orders_items.js
Labels: database

#112 feature(collection): Resolve console error in collection page
  packages/client/src/ProductPropType.js
  packages/client/src/components/CategoriesListDropDown/CategoriesListDropDown.component.js
  packages/client/src/components/CategoriesListDropDown/CategoriesListDropDown.style.css
  packages/client/src/components/ProductList/ProductList.component.js
  packages/client/src/containers/CollectionsPage/CollectionsPage.Container.js
Labels: bug, frontend, Search_team
