Repository HackYourFuture-CPH/fp-class22, pull requests merged in 2023-01, with the labels that each got.

#116 feat(dynamic navigation):adding icons to the navigation once the user…
  packages/client/src/assets/icons/Favorite.png
  packages/client/src/assets/icons/shopping.png
  packages/client/src/assets/icons/user.png
  packages/client/src/components/Navigation/Navigation.component.js
  packages/client/src/components/Navigation/Navigation.styles.css
Labels: approved

#111 feature(ProductViewBreadcrumbs): added link to collections page in th…
  packages/client/src/containers/ProductView/ProductView.container.js
  packages/client/src/containers/ProductView/index.js
  packages/client/src/containers/ProductViewBreadcrumbs/ProductViewBreadcrumbs.container.js
  packages/client/src/containers/ProductViewBreadcrumbs/ProductViewBreadcrumbs.styles.css
Labels: frontend, View_team

#107 Class22 131 feature add partial functionality on shopping cart page
  packages/client/src/components/Cart/CartSelectedProduct/CartSelectedProduct.component.js
  packages/client/src/components/Cart/CartTable/CartTable.component.js
  packages/client/src/components/Cart/CartTotal/CartTotal.component.js
  packages/client/src/containers/ShoppingCartPage/ShoppingCartPage.container.js
Labels: View_team

#125 Class22 127 remove favorites confirmation via modal
  packages/client/src/components/Modal/Modal.component.js
  packages/client/src/components/ProductCard/ProductCard.component.js
  packages/client/src/components/ViewPageButton/ViewPageButton.component.js
  packages/client/src/containers/FavoritesPage/FavoritesPage.container.js
Labels: Search_team

#123 feature(Order endpoint) create order endpoint
  packages/server/api/controllers/orders.controller.js
  packages/server/api/routes/index.js
  packages/server/api/routes/orders.router.js
  packages/server/seeds/development/users.js
  packages/server/seeds/development/w_orders_items.js
Labels: backend, Search_team

#120 Refactor(products endpoint) to consider user and favorites
  packages/client/src/components/ProductList/ProductList.component.js
  packages/client/src/containers/CollectionsPage/CollectionsPage.Container.js
  packages/server/api/controllers/products.controller.js
  packages/server/api/controllers/users.controllers.js
  packages/server/api/routes/favorites.router.js
  packages/server/api/routes/index.js
  packages/server/api/routes/products.router.js
  packages/server/api/routes/users.router.js
Labels: backend, Search_team

#121 Refactor(Favorites get endpoint): add user authorization
  packages/client/src/containers/FavoritesPage/FavoritesPage.container.js
  packages/server/api/controllers/favorites.controller.js
  packages/server/api/routes/favorites.router.js
  packages/server/seeds/development/v-favorites.js
Labels: backend, Search_team

#137 fix error on carousel related item
  packages/server/api/controllers/products.controller.js
Labels: backend, View_team

#132 feature(order_items): post new order item
  packages/server/api/controllers/orders.controller.js
  packages/server/api/routes/orders.router.js
Labels: backend, View_team

#106 feature(shoppingCart): adds shopping cart context
  packages/client/src/App.js
  packages/client/src/components/Cart/CartButtons/CartButtons.component.js
  packages/client/src/components/Cart/CartSelectedProduct/CartSelectedProduct.component.js
  packages/client/src/components/Cart/CartSelectedProduct/CartSelectedProduct.styles.css
  packages/client/src/components/Cart/CartTable/CartTable.component.js
  packages/client/src/components/Cart/CartTable/CartTable.styles.css
  packages/client/src/components/Navigation/Navigation.component.js
  packages/client/src/containers/DropdownGroup/DropdownGroup.Container.js
  packages/client/src/containers/ShoppingCartPage/ShoppingCartPage.container.js
  packages/client/src/utils/ShoppingCartContext/ShoppingCartContext.jsx
  packages/server/api/controllers/orders.controller.js
  packages/server/api/routes/orders.router.js
Labels: frontend, View_team

#128 Feature (Add uid to db)
  packages/client/src/App.js
  packages/client/src/components/Navigation/Navigation.component.js
  packages/client/src/containers/Signup/Signup.container.js
  packages/client/src/containers/Signup/Signup.styles.css
  packages/client/src/containers/Signup/SignupForm.js
  packages/client/src/userContext.js
  packages/client/src/utils/hooks/useInputValidation.jsx
  packages/client/src/utils/validateForm.js
  packages/server/api/controllers/users.controller.js
  packages/server/api/controllers/users.controllers.js
  packages/server/api/routes/users.router.js
Labels: backend

#141 added-404-page-for-no-product-in-database
  packages/client/src/App.js
  packages/client/src/containers/DropdownGroup/DropdownGroup.Container.js
  packages/client/src/containers/ProductView/ProductView.container.js
Labels: frontend, View_team

#142 feature(fix collection page) category dropdown fix fetching error
  packages/client/src/components/CategoriesListDropDown/CategoriesListDropDown.style.css
  packages/client/src/containers/CollectionsPage/CollectionsPage.Container.js
Labels: bug, frontend, Search_team

#144 fix(order_items): post order_items and shopping cart products amount in nav bar
  packages/client/src/components/Cart/CartSelectedProduct/CartSelectedProduct.component.js
  packages/client/src/components/Cart/CartTable/CartTable.component.js
  packages/client/src/components/Navigation/Navigation.component.js
  packages/client/src/containers/ShoppingCartPage/ShoppingCartPage.container.js
  packages/client/src/utils/ShoppingCartContext/ShoppingCartContext.jsx
  packages/server/api/controllers/orders.controller.js
Labels: frontend, backend

#138 feature(DropdownGroup.container): Displaying the size and quantity ba…
  packages/client/src/components/ViewDropDown/ViewDropdown.component.js
  packages/client/src/containers/DropdownGroup/DropdownGroup.Container.js
  packages/server/api/routes/variants.router.js
Labels: frontend, backend, View_team

#143 Class22 129 switching page buy now button at product page
  packages/client/src/containers/DropdownGroup/DropdownGroup.Container.js
  packages/client/src/containers/ProductView/ProductView.container.js
  packages/client/src/containers/ProductView/ProductViewButtons/ProductViewButtons.container.js
  packages/client/src/utils/ShoppingCartContext/ShoppingCartContext.jsx
  packages/server/seeds/development/3_users.js
  packages/server/seeds/development/4_orders.js
  packages/server/seeds/development/8_orders_items.js
Labels: frontend, Search_team

#147 fix(ShoppingCart): selecting and deleting items from cart
  packages/client/src/components/Cart/CartSelectedProduct/CartSelectedProduct.component.js
  packages/client/src/components/Cart/CartTable/CartTable.component.js
  packages/client/src/containers/ShoppingCartPage/ShoppingCartPage.container.js
  packages/client/src/utils/ShoppingCartContext/ShoppingCartContext.jsx
Labels: frontend, View_team

#146 uid fix
  packages/client/src/containers/Signup/Signup.container.js
  packages/client/src/containers/Signup/Signup.styles.css
  packages/client/src/containers/Signup/SignupForm.js
  packages/client/src/userContext.js
Labels: Landing_team

#145 fix image on related item
  packages/client/src/components/ProductReviews/ProductReviews.styles.css
  packages/client/src/containers/DropdownGroup/DropdownGroup.Style.css
  packages/client/src/containers/ProductView/ProductView.styles.css
  packages/client/src/containers/RelatedItems/RelatedItems.styles.css
Labels: frontend, View_team

#148 Refactor(Footer, Header ) add semantic tags
  packages/client/src/components/Footer/Footer.component.js
  packages/client/src/components/Navigation/Navigation.component.js
Labels: frontend, Search_team

#149 post-delete-end-point-of-favourites:
  packages/server/api/controllers/favorites.controller.js
  packages/server/api/routes/favorites.router.js
Labels: backend, Search_team

#139 Class22 156 delete favorites confirmation via modal
  packages/client/src/components/ProductCard/ProductCard.component.js
  packages/client/src/components/ProductList/ProductList.component.js
  packages/client/src/containers/CollectionsPage/CollectionsPage.Container.js
  packages/client/src/containers/FavoritesPage/FavoritesPage.container.js
  packages/server/api/controllers/favorites.controller.js
  packages/server/api/routes/favorites.router.js
  packages/server/seeds/development/3_users.js
  packages/server/seeds/development/5_favorites.js
Labels: Search_team

#151 Class22 167 choose dropdown options modal on click button buy now and add to cart
  packages/client/src/containers/ProductView/ProductView.container.js
  packages/client/src/containers/ProductView/ProductView.styles.css
Labels: frontend, styling, Search_team

#153 feature(fix bug in Category endpoint) add user authantication
  packages/server/api/controllers/products.controller.js
  packages/server/api/routes/products.router.js
Labels: bug, backend, database
